<?php

namespace JH\TourismeBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByDepartment($id)
    {
        return $this
            ->createQueryBuilder("c")
            ->innerJoin("c.department", "d")
            ->where("d.id = :id")
                ->setParameter("id", $id)
            ->getQuery()
            ->getArrayResult()
        ;
    }
}
