<?php

namespace JH\TourismeBundle\Repository;

/**
 * DepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByRegion($id)
    {
        return $this
            ->createQueryBuilder("d")
            ->innerJoin("d.region", "r")
            ->where("r.id = :id")
                ->setParameter("id", $id)
            ->getQuery()
            ->getArrayResult()
        ;
    }
}
