home:
    path: /
    defaults: { _controller: JHTourismeBundle:Tourisme:home }
    
add_activity:
    path: /activite/ajouter
    defaults: { _controller: JHTourismeBundle:Activity:add }
    
view_activity:
    path: /activite/voir/{id}
    defaults:
        _controller: JHTourismeBundle:Activity:view
    requirements:
        id: \d+